### ISSUE TITLE
java-client broken with Onshape upgrade on 03/09

### ISSUE THREAD

**Issue by treddy16** [onshape-public/java-client#23]
I am getting this error after the upgrade:

**com.onshape.api.exceptions.OnshapeException: Invalid formatName argument.**
	at com.onshape.api.base.BaseClient.call(BaseClient.java:513)
	at com.onshape.api.base.BaseClient.call(BaseClient.java:333)
	at com.onshape.api.requests.TranslationsCreateTranslationRequest$Builder.call(TranslationsCreateTranslationRequest.java:527)
	at com.cassinisys.pdm.onshape.TestOnshape.uploadPartsInDirectory(TestOnshape.java:54)
	at com.cassinisys.pdm.onshape.TestOnshape.createParts(TestOnshape.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

This was working before. Did something change? Do you need to update the java-client?

**Comment by harmanpa** [comment]
Were you using the "ONSHAPE" format name? I think @ethan92429 said that was being removed in favour of other methods for uploading?

**Comment by treddy16** [comment]
Yes, I am using ONSHAPE format. What is the other translation method?

**Comment by treddy16** [comment]
So, this method  has been removed in this upgrade, I am assuming.

**Comment by awk** [comment]
We became aware of this yesterday from some internal testing. We're working on a fix - if you can send email to api-support (at) onshape.com we can link your ticket to the fix so that you're notified when the fix is deployed.

(A general note too - we do monitor github issues and the like, however it's nearly always best to begin with an email to api-support since it allows us to link things together in our internal systems. Especially when the problem is not actually a change to a library but rather a server side issue).

**Comment by harmanpa** [comment]
@treddy16 The following should give you the same without needing the "ONSHAPE" translation target:
```java
  BlobElementsUploadFileCreateElementResponse uploadResponse = onshape.blobElements().uploadFileCreateElement().file(Blob.fromFile(<file>)).translate(true).call(<did>, <wid>);
  Future<TranslationsGetTranslationResponse> translation = onshape.translations().getTranslation().call(uploadResponse.getTranslationId()).asFuture(onshape);
  TranslationsGetTranslationResponse completedTranslation = translation.get();
```

**Comment by treddy16** [comment]
Will give this a shot. Thanks!

**Comment by treddy16** [comment]
I have tried the suggested method and I get FAILED for status of translation. I see the file has been uploaded. But no translation. Here is the notification inside Onshape

![image](https://user-images.githubusercontent.com/4503972/77219534-b3725800-6b5c-11ea-8aac-d61e19ef90c4.png)
