### ISSUE TITLE
Possible to get a jakarta version for java 9 and java 11?

### ISSUE THREAD

**Issue by joshuadwinn** [onshape-public/java-client#37]
Javax dependencies make it difficult to move forward to newer versions of java.  Can we get the FactoryFinder updated to find a jakarta library and update the inputstreamswithheader to use jakarta?

**Comment by harmanpa** [comment]
We have a jakarta version here: https://github.com/harmanpa/onshape-client

**Comment by joshuadwinn** [comment]
I'm unable to pull it down, is this published to mavencentral or jcenter? I'm using gradle to try to pull it down using the jakarta release.

`**org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException**: Could not resolve all files for configuration 'REDACTED'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1176)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2100(DefaultConfiguration.java:136)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1151)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:72)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:463)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:384)
	at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.addAll(ImmutableCollection.java:476)
	at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:518)
	at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:80)
______________________________________
Caused by: **org.gradle.internal.resolve.ModuleVersionNotFoundException**: Could not find com.github.harmanpa.onshape-client:onshape-endpoints-jakarta:v1.152.6309.06d9e62c38f0.
Required by:
    project :REDACTED> project :REDACTED
	at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:42)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainCom
	... 127 more
`

**Comment by harmanpa** [comment]
You added Jitpack to the repositories list?

```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

**Comment by joshuadwinn** [comment]
Yes I did add that.

**Comment by joshuadwinn** [comment]
I had to change the implementation based on jitpack.io.  It's this for gradle:
implementation 'com.github.harmanpa:onshape-client:v1.152.6309.06d9e62c38f0'
